baseurl = "/"
languageCode = "en-us"
title = "The Bayesian Bird"
theme = "hugo-lithium"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
enableEmoji = true

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "About"
    url = "/about/"
[[menu.main]]
    name = "Linkedin"
    url = "https://www.linkedin.com/in/ortegavce/"
[[menu.main]]
    name = "GitHub"
    url = "https://github.com/CarlosOrtegaV/"
[[menu.main]]
    name = "Twitter"
    url = "https://twitter.com/CarlosOrtegaVz"

[params]
    description = "A website built through Hugo and blogdown."

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.11.0"
    highlightjsCDN = "//cdn.bootcss.com"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdn.bootcss.com"
    MathJaxVersion = "2.7.1"

    [params.logo]
    url = "duck_logo.png"
    width = 50
    height = 50
    alt = "Logo"

